[manager]
ratio = [1, 2, 4]
sort_by = "natural"
sort_sensitive = true
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 5

[opener]
edit = [
  # editor
  { run = 'nvim "$@"', block = true, for = "unix" },
]
open_terminal = [
  # system app
  { run = 'cd "$@"', desc = "Open terminal", for = "macos" },
]
open = [
  # system app
  { run = 'open "$@"', desc = "Open", for = "macos" },
]
reveal = [
  # reveal
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
]
extract = [
  # extract
  { run = 'unar "$1"', desc = "Extract here", for = "unix" },
]
play = [
  # media
  { run = 'vlc "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
  # rules for open file
  { name = "*/", use = ["edit", "open"] },

  { mime = "text/*", use = ["edit", "reveal"] },
  { mime = "image/*", use = ["open", "reveal"] },
  { mime = "video/*", use = ["play", "reveal"] },
  { mime = "audio/*", use = ["play", "reveal"] },
  { mime = "inode/x-empty", use = ["edit", "reveal"] },

  { mime = "application/json", use = ["edit", "reveal"] },
  { mime = "*/javascript", use = ["edit", "reveal"] },

  { mime = "application/zip", use = ["extract", "reveal"] },
  { mime = "application/gzip", use = ["extract", "reveal"] },
  { mime = "application/x-tar", use = ["extract", "reveal"] },
  { mime = "application/x-bzip", use = ["extract", "reveal"] },
  { mime = "application/x-bzip2", use = ["extract", "reveal"] },
  { mime = "application/x-7z-compressed", use = ["extract", "reveal"] },
  { mime = "application/x-rar", use = ["extract", "reveal"] },
  { mime = "application/xz", use = ["extract", "reveal"] },

  { mime = "*", use = ["open", "reveal"] },
]
