[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

# skip word left
[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

# Skip word left
[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

# delete lines
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

# Delete word
[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

# close tab
[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

# command + T  new tab
[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

# command + [1-9] for window [1-9]
[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"

# Command + N new window horizontal
[[keyboard.bindings]]
chars = "\u0001\""
key = "N"
mods = "Command"

#new window vertical 
[[keyboard.bindings]]
chars = "\u0001%"
key = "N"
mods = "Command|Shift"

# new tmux session
[[keyboard.bindings]]
chars = "\u0001s"
key = "K"
mods = "Command"

# rename session
[[keyboard.bindings]]
chars = "\u0001,"
key = "Comma"
mods = "Command"

# attach session
[[keyboard.bindings]]
chars = "\u0001s"
key = "A"
mods = "Command"

# detach session
[[keyboard.bindings]]
chars = "\u0001d"
key = "D"
mods = "Command"

# neovim save
[[keyboard.bindings]]
chars = """
\u001B:w
"""
key = "S"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.97
startup_mode = "Windowed"

[window.padding]
x = 0
y = 0
